steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/w2v-api', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/w2v-api']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
    - 'run'
    - 'deploy'
    - 'w2v-api'
    - '--image'
    - 'gcr.io/$PROJECT_ID/w2v-api'
    - '--region'
    - 'asia-northeast1'
    - '--platform'
    - 'managed'
    - '--memory'
    - '4Gi'
    - '--cpu'
    - '2'
    - '--port'
    - '8080'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'S3_BUCKET=my-w2v-models-2024,AWS_REGION=ap-northeast-1'

images:
- gcr.io/$PROJECT_ID/w2v-api