version: '3.8'

services:
  # Word2Vec Association API
  w2v-api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      # モデルファイルを外部ボリュームからマウント
      - models_data:/app/entity_vector
      - ./swagger.yaml:/app/swagger.yaml:ro
    environment:
      - MODEL_PATH=/app/entity_vector
      - API_PORT=8080
      - LOG_LEVEL=INFO
    depends_on:
      - model-downloader
    restart: unless-stopped

  # モデルファイルダウンローダー（初回セットアップ用）
  model-downloader:
    image: alpine/curl:latest
    volumes:
      - models_data:/data
    command: >
      sh -c "
        if [ ! -f /data/entity_vector.model.bin ]; then
          echo 'モデルファイルをダウンロード中...'
          curl -L -o /data/entity_vector.model.bin 'https://example-storage.com/models/entity_vector.model.bin'
          echo 'ダウンロード完了'
        else
          echo 'モデルファイルは既に存在します'
        fi
      "
    restart: "no"

  # Redis（キャッシュ用・オプション）
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  # モデルファイル用の永続ボリューム
  models_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/models  # ホストの ./models ディレクトリ
  
  # Redis データ用
  redis_data:
    driver: local